name: My-GitHubActions

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: run-script phpcs -- --standard=PSR12
      run: Run make lint

    # - name: Run test suite
    #   run: composer run-script test
