name: My-GitHubActions

on:
  - push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v1
        with:
          # Specify the PHP version
          php-version: '7.4'

      - name: Run linter
        run: |
          make lint

